# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle CI (Java 21)

on:  
  pull_request:
    branches: [ master ]
    
  push:
    paths:
      - 'src/**'
      - '**.yml'
      - '**.gradle'
      - '**.properties'
      
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#noci')"

    steps:
    - uses: actions/checkout@v4.1.0
      name: Checkout
      
    - name: Set up JDK 21
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '21'
        distribution: 'zulu'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3.3.2
      with:
        arguments: build
        
    - name: Export to JAR
      uses: gradle/gradle-build-action@v3.3.2
      with:
        arguments: jar
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: ./build/libs/*.jar
